### ISSUE TITLE
The current source has been sunsetted and not maintained since 2015

### ISSUE THREAD

**Issue by y2kbugger** [conda-forge/bumpversion-feedstock#1]
The current fork is located at: https://github.com/andrivet/advbumpversion

The owner of the current source has stated it here: https://github.com/peritus/bumpversion/issues/169
> I should probably add a sunsetting notice to the top of the README, saying this is not actively maintained and people should switch to one of the forked versions.

**Comment by nicoddemus** [comment]
Thanks for the note.

Given that the name of the package has changed to `advbumpversion`, it seems it should have its own feedstock.
